A) SELECT * FROM TALHAO WHERE TALH_CODIGO_PROP = 20 AND TALH_SAFRA = 2021 ORDER BY TALH_CODIGO ASC;

B) SELECT SUM(PROP_AREA) FROM PROPRIEDADE_AGRICOLA;

C) SELECT * FROM TALHAO WHERE TALH_CODIGO > 15 AND TALH_CODIGO_PROP = 5 ORDER BY TALH_CODIGO ASC;

D) SELECT COUNT(*) FROM TALHAO WHERE TALH_SAFRA = 2020;

E) SELECT COUNT(*) FROM TALHAO WHERE TALH_CODIGO_PROP = 10 AND TALH_SAFRA = 2021;